#!/usr/bin/env bash
# This script configures an Ubuntu server as follows:
#   - localhost resolves to 127.0.0.2
#   - facebook.com resolves to 8.8.8.8

# Copy the hosts file to the user's home directory and give it a new name
cp /etc/hosts ~/hosts.new

# Add an entry for localhost to the new hosts file
echo "127.0.0.2		localhost" > ~/hosts.new

# Add an entry for facebook.com to the new hosts file
echo "8.8.8.8		facebook.com" >> ~/hosts.new

# Copy the new hosts file forcefully (-f option) back to its original location
cp -f ~/hosts.new /etc/hosts

